name: SSH into EC2
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
    - name: SSH into EC2
      run: |
            ssh  -i ${{ secrets.EC2_SSH_KEY }} ec2-user@${{ secrets.HOST_DNS}} << 'EOF'
            docker pull hello-world
            docker run -d --name hello-world-container hello-world
            EOF