name: Deploy to EC2

on: [push]  # Trigger on pushes to a specific branch or event

jobs:
  deploy:
    runs-on: ubuntu-latest  # Or a suitable runner for SSH

    steps:
      - uses: actions/checkout@v3

      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME}}
          key: ${{ secrets.EC2_SSH_KEY }}

      - name: Create dockerpull.sh on EC2
        run: |
          echo "${{ secrets.DEPLOY_SCRIPT_CONTENTS }}" > dockerpull.sh
          chmod +x dockerpull.sh

      - name: Run deploy.sh on EC2
        run: |
          ./dockerpull.sh
